apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-react-app
  labels:
    app: chatbot-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-react-app
  template:
    metadata:
      labels:
        app: chatbot-react-app
    spec:
      containers:
      - name: chatbot-react-app
        image: llmrepooow.azurecr.io/chatbot-react-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_LLM_ENDPOINT
          value: http://4.158.38.213/chat
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-react-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: chatbot-react-app
