apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-tuning-falcon-7b-instruct
resource:
  instanceType: Standard_NC12s_v3
  labelSelector:
    matchLabels:
      apps: tuning-falcon-7b-instruct
tuning:
  preset:
    name: falcon-7b
  method: qlora
  input:
    urls: 
      - https://oowpublic.blob.core.windows.net/parquet/microsoft_products_tuning_data.parquet
  output:
    image: llmrepooow.azurecr.io/adapters/myadapter:0.0.1
    imagePushSecret: acr-secret
